name: MinecraftSmashHeroes
version: '${project.version}'
main: me.tammon.minecraftsmashheroes.MinecraftSmashHeroes
api-version: '1.20'
authors: [Tammon]
description: A recreation of Hypixel's Smash Heroes
commands:
  setHero:
    description: Used to set the hero of the caller of the command
    usage: /setHero <hero_name>
  getCustomItem:
    description: Used to get custom hero items
    usage: /getCustomItem <item_name>
  summonVehicle:
    description: Used to summon a vehicle that can be ridden
    usage: /summonVehicle <vehicle_name>
  drawLine:
    description: Draws a line over a given distance
    usage: /drawLine <distance>
  dash:
    description: Dashes user a distance forward
    usage: /dash [distance]